networks:
  snappy-green-frog:
    driver: bridge
    name: snappy-green-frog
services:
  caddy:
    image: caddy:latest
    networks:
    - snappy-green-frog
    - default
    ports:
    - 80:80
    volumes:
    - ./configs/Caddyfile:/etc/caddy/Caddyfile
  db:
    environment:
      POSTGRES_MULTIPLE_DATABASES: rekuest,kabinet,mikro,fluss,lok,kraph
      POSTGRES_PASSWORD: 30ae0f6d873a75e6ca8d25f98033f849
      POSTGRES_USER: sleepyviolettarsier
    image: jhnnsrs/daten:dev
    volumes:
    - ./db_data:/var/lib/postgresql/data
  deployerglobal:
    command: arkitekt-next run prod --redeem-token=3e4971887b83bfd317e064103ff762f0
      --url http://gateway:80
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10
        window: 300s
    environment:
      ARKITEKT_GATEWAY: http://gateway:80
      ARKITEKT_NETWORK: snappy-green-frog
      DEPLOYER_ORGANIZATION: global
      INSTANCE_ID: default
    image: jhnnsrs/deployer:dev
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    network:
    - snappy-green-frog
  fluss:
    command: bash run.sh
    depends_on:
    - redis
    - db
    - minio
    image: jhnnsrs/fluss:dev
    volumes:
    - ./configs/fluss.yaml:/workspace/config.yaml
  kabinet:
    command: bash run.sh
    depends_on:
    - redis
    - db
    - minio
    image: jhnnsrs/kabinet:dev
    volumes:
    - ./configs/kabinet.yaml:/workspace/config.yaml
  kraph:
    command: bash run.sh
    depends_on:
    - redis
    - db
    - minio
    image: jhnnsrs/kraph:dev
    volumes:
    - ./configs/kraph.yaml:/workspace/config.yaml
  lok:
    command: bash run.sh
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10
        window: 300s
    image: jhnnsrs/lok:dev
    volumes:
    - ./configs/lok.yaml:/workspace/config.yaml
  mikro:
    command: bash run.sh
    depends_on:
    - redis
    - db
    - minio
    image: jhnnsrs/mikro:dev
    volumes:
    - ./configs/mikro.yaml:/workspace/config.yaml
  minio:
    command: server /data
    environment:
      MINIO_ROOT_PASSWORD: 03r0sqo6k0hycir72mmh67vtckv954yyob7nmdak
      MINIO_ROOT_USER: snazzy-mauve-birman
    image: minio/minio:RELEASE.2025-02-18T16-25-55Z
    volumes:
    - ./data:/data
  minio_init:
    depends_on:
      minio:
        condition: service_started
    environment:
      MINIO_HOST: http://minio:9000
      MINIO_ROOT_PASSWORD: 03r0sqo6k0hycir72mmh67vtckv954yyob7nmdak
      MINIO_ROOT_USER: snazzy-mauve-birman
    image: jhnnsrs/init:dev
    volumes:
    - ./configs/minio_init.yaml:/workspace/config.yaml
  redis:
    image: redis:latest
  rekuest:
    command: bash run.sh
    depends_on:
    - redis
    - db
    - minio
    image: jhnnsrs/rekuest:dev
    volumes:
    - ./configs/rekuest.yaml:/workspace/config.yaml
