csrf_trusted_origins: []
db:
  db_name: kraph
  engine: django.db.backends.postgresql
  host: db
  password: 30ae0f6d873a75e6ca8d25f98033f849
  port: 5432
  username: sleepyviolettarsier
django:
  admin:
    email: null
    password: sdf
    username: admin
  debug: false
  hosts:
  - '*'
  secret_key: 6g=4+oj=qo%g_9yj_(**f@w%f05)ns*_&^!^sl2+rsvg-c_6c0
force_script_name: kraph
lok:
  issuer: lok
  key_type: RSA256
  public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8k1ZePcYUf6fPWhGOp5hz8Mpfuks7GtVugrWdUmC2LWDCHeLfnVpR3po07hKDKIOcTFgN7MmxOxPrNKNsj2SN26d3Pbr8UFUdOHG0xaV5XtcVac+FPGnxJ9zYA8UbXTKpRLYkTzsTbUKlBqEiEWCNfXnhRQs3xi5xT6A/SMkRxjMTh2+hx0Gc9mixPxgEGaxR1HXzneXB9IPhlQwZ8ZBtNaIKAweGnvYrzR2GDjSDphHKHyz+yBUt27xjUeR9lMy+I1VxRSfzfkwc2jVs2ZnSqKg/LYaV87DU8Y/SRhv1V2fi+2+EnXABbZStrpLupOBx3vmo6SuylnegaeuSajBV
redis:
  host: redis
  port: 6379
s3:
  access_key: 0guum8kdxfho2erjb1chi6tot2o9qagzrotc9y0u
  buckets:
    media: crabby-sapphire-alligator
  host: minio
  port: 9000
  protocol: http
  secret_key: m70nvh278sxd1acrnfpzf72xirle8yglhl9blyw9
