buckets:
- name: stealthy-cyan-rhinoceros
- name: grumpy-smalt-civet
- name: hazy-pink-mouse
- name: snippy-fuchsia-eagle
- name: snoopy-purple-akita
- name: frumpy-charcoal-weasel
- name: wiggy-zucchini-coyote
- name: crabby-sapphire-alligator
users:
- access_key: 0guum8kdxfho2erjb1chi6tot2o9qagzrotc9y0u
  name: Default User
  policies:
  - readwrite
  secret_key: m70nvh278sxd1acrnfpzf72xirle8yglhl9blyw9
